### ISSUE TITLE
How to add (many more) zmq pipes?

### ISSUE THREAD

**Issue by thebaldgeek** [muaddib1984/gr-JAERO#3]
Sorry for the basic question, but how do I specify the topic for each Jaero ZMQ channel?

Generally I run around 20 Jaeros, each on a different topic from SRReceiver, but with gr-JAERO I can not find how to specify each topic or run more than one flow graph with a different topic.

**Comment by muaddib1984** [comment]
No apology needed. Sorry if that’s not clear. When you open the example flowgraph, There’s a section in the JAERO ZMQ PUB socket. That has a field called “TOPIC”. That will get sent to JAERO along with the sample rate. 
I haven’t tried this with multiple jaero instances yet but (depending on SNR) you could probably send an unfiltered sideband containing multiple 600/1200bps carriers by connecting the ‘audio 16 bit out’  to multiple JAERO ZMQ PUB sockets. They can be drag-and-dropped from the blocks sidebar in GNURadio Companion.  Each one would need a different IP Port and a different topic similar to SDRReceiver. 
Then you’d setup each JAERO instance to connect to a port/topic like SDRReceiver.

**Comment by thebaldgeek** [comment]
I am going to be honest and say I only roughly follow... I see the block and have changed the topic to VFO01 to match what I had in SDRReceiver, so far so good (but no ACARS in Jaero yet, its an odd looking wave on its blue graph! Data LED is green, volume is grey as is data).
How exactly do I add another 19 across the whole L-Band?
Will I get 19 images in the waveforms GUI since the voice, 600, 1200 and 10500 all need different settings?

**Comment by muaddib1984** [comment]
I'm looking at the multiple channel piece right now. At this moment, I'm decoding a 1200bps channel using an RTL L-Band patch antenna and an RTLSDR V3 Dongle. 
Let's get you decoding a single channel first as I have done that successfully (have not tried multiple channels yet).

Re: the grey LED's. 
As you know, it's usually best to have volume/signal/data as green-green-green. 
There are audio volume and VFO Low-Pass Gain sliders for your signal level into JAERO. 
I've found that with slightly below average SNR, the audio needs to be at around 10 and low-pass gain needs to be up around 6-7 but it's SNR dependent. 

If you're turned up all the way and that's still not working. If you want to pump more signal into JAERO, you can raise the maximum possible range of the volume sliders very simply by opening the flowgraph and double clicking the respective blocks in GRC. Change the 'stop' value higher. That will give the slider more room to move.

**Comment by muaddib1984** [comment]
@thebaldgeek Ok, i may have given a not-so-great answer, but here's what i'm talking about regarding multiple JAERO's.

Correct me if i'm wrong, but after digging through the SDRReceiver code quite a bit my understanding is that SDRReceiver takes a big chunk of spectrum and 'cuts' it into smaller chunks based on what you want to decode (the config file dictates the 'chunks'). It then outputs each one on a separate ZMQ socket. 
gr-JAERO doesn't _exactly_ support the multi-channel output out-of-the-box with the included examples as I tried to keep it simple and very visual for beginners. However, because of the immense flexibility within GNURadio, it can absolutely be done with some slight reworking. I will get an example there eventually, but you know...not enough hours in the day!

What it *does* do is pass the _entire_ spectrum directly into JAERO at 48ksps. You can connect as many downstream JAERO's as you want to the _single_ stream (same ZMQ topic and port). Then you just select the channel you want in each window as shown here.

![image](https://user-images.githubusercontent.com/70996692/159198502-70b3d3ab-0f96-470a-82b5-f2648d62429c.png)

The downside to this is that you don't get the per-channel digital filtering of SDRReceiver.
The ideal way to to that would be to drop more USB Demodulator blocks and JAERO ZMQ PUB blocks in the flowgraph. They'll be operating on the same main stream (Main VFO in SDRReceiver) stream and then enter your filter/LO parameters (VFO) for each SDRReceiver VFO there. I'm not sure how user friendly this will be as far as translating the SDRReceiver config files, but it's definitely do-able. The concepts are the same. 
For a quick proof-of-concept i've done just that, added a second USB Demodulator block (no GUI widgets for now) and connected that to a second JAERO ZMQ PUB block with a different ZMQ IP port. 
So I have 2 JAERO's running on the ZMQ 6001 port each decoding a different channel and then I also have 1 running on the 6002 port. The advantage to the 6002 port is that after I shift the spectrum (LO/VFO), I can apply low-pass filtering. That will 'zero in' on just that specific channel. Filtering is a beautiful thing, but not always needed. Again, it's SNR specific. 
![image](https://user-images.githubusercontent.com/70996692/159200155-bba3746f-a403-4dda-a4eb-bdc871d85cf5.png)
![image](https://user-images.githubusercontent.com/70996692/159200752-55335104-2f16-46d4-b0a5-195a9718b75b.png)

I REALLY hope this wasn't confusing, i'm prone to 'thought streaming' with my keyboard. Check this out and let me know what works.

I'm also VERY curious about whether or not you can get the C-Band stuff working as I have been limited to only L-Band due to my current hardware.

**Comment by thebaldgeek** [comment]
Thank-you for the very comprehensive reply! The extra detail is very very helpful in understanding whats going on and how we can bend it to our use case.   
The main place I'd like to press gr-JAERO into service is on C-Band. SDRReceiver is set up and running on 143E (Aust), 98W (me in California) and 25E (UK). It works well there as you can see the L-Band data channel bumps and its easy to convert from something like SDR++ to SDRReceiver's .ini file.
   
The other two stations have spent around 12 hours on their stations, I have spent around 70 to 80 hours trying to get SDRReceiver to work on C-Band to no effect. Because the C-Band data is burst, there is no 'bump' that you can see, so its just a matter of blindly changing the .ini file and testing over and over and over. 
I was really hoping the live spectrogram here would show C-Band burst data and so we could get going. I started yesterday with L-Band since its known quality and will move to C-Band once I have some confidence in the easiest band to get going.

Here is a screenshot of 143E C-Band.
![image](https://user-images.githubusercontent.com/7385116/159257818-159c9fc6-cf12-4640-9b56-8681601e251c.png)

We will need to have a ZMQ data channel where every yellow channel is parked. Keep in mind that there are two types of C-Band data, you can see the fat 10500 on the right and the narrow super bursty 1200 data on the left. We will need to cover both. And yes, we run around 25 Jaeros for C-Band not including the voice downlinks which can run another 7 to 12 Jaeros.

**Comment by muaddib1984** [comment]
I think your use case makes sense, but maybe not using the current flowgraphs. I'd like to work with you on it if that's OK and perhaps get something a little more conducive to your specific application.

If you're interested,I'll start a Dev branch with some ideas on how we might accomplish this.

**Comment by thebaldgeek** [comment]
Just checking in with this project, I see the front page has been updated, but looks like there is still only one output channel?

**Comment by muaddib1984** [comment]
sorry i missed the notification, i've been head-down in 'dish land'. Yes, i was able to get my own C-Band setup working and successfully decode 10500 bursts. I'm working on multi-channel for the project as we speak, but it hasn't been updated for multi-channel yet.
I should have a final working example with instructions in the next week or so. 
As i'm honing the user experience, i'd like to use your use case as an example as it seems we can test it out. For a first shot i'm going to work on RTL-SDR compatible sample rates and focus mostly on C-Band so that should work for you i think.
What are your typical target sample rates/bandwidths for your US/UK/AU stations?

**Comment by thebaldgeek** [comment]
No worries, life first, hobbies latter.    
I would assume you live under one of the 4 Inmarsats sat's that one of us does, so the rates for me are the same for you.     
10,500, 1200 and 8400 (for voice).
What differs between the 4 sats is the number of channels and combinations of them.

**Comment by muaddib1984** [comment]
yes, agreed on life priorities. You are correct about us being under the same sky, i'm seeing 98W at my location (US) i believe. WIth the rates, Let me clarify my question, what is your _overall_ sample rate for your SDR. Like the whole bandwidth you're taking in. Based on the screenshot above it's somewhere around 500ksps/500kHz to 1Msps/1MHz? I'm implementing polyphase channelization which is a fancy DSP way of splitting apart a large chunk of spectrum into smaller pieces, i'm trying to make it flexible enough to where the sample rate/bandwidth can be adjusted as needed, but I may have some maximums/minimums like for example "this only works with between 1 and 2 Msps", that's just an example, but I'd like to tailor to your use case a bit instead of setting out parameters that don't work right off the bat. 
C-Band 10500 burst seems to typically fit within 1MHZ but i'm still exploring it and developing the best case, so i'll rely on your case. Based on your site, I believe our hardware is the same or comparable. I use several different SDR's and my dish is only a 99cm, but i'm still getting 10dB on the burst signals. So with the exception of geographic proximity, I should be able closely simulate your setup.

**Comment by muaddib1984** [comment]
Closing this issue. I added a special branch called cbandhunter which is a totally custom application that addresses this specific issue. Feel free to open a new issue if you have trouble using cbandhunter.
